<?php
/**
 * DocumentMetadataTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\media
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Media API
 *
 * The <b>Media API</b> lets sellers to create, upload, and retrieve files, including:<ul><li>videos</li><li>documents (for GPSR regulations)</li></ul>
 *
 * The version of the OpenAPI document: v1_beta.2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace macropage\SDKs\ebay\rest\media\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DocumentMetadataTest Class Doc Comment
 *
 * @category    Class
 * @description This type provides information about the &lt;b&gt;documentId&lt;/b&gt;.
 * @package     macropage\SDKs\ebay\rest\media
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DocumentMetadataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DocumentMetadata"
     */
    public function testDocumentMetadata()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fileName"
     */
    public function testPropertyFileName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fileSize"
     */
    public function testPropertyFileSize()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fileType"
     */
    public function testPropertyFileType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
