<?php
/**
 * VideoApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\media
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Media API
 *
 * The Media API allows sellers to create, upload, and fetch videos.
 *
 * The version of the OpenAPI document: v1_beta.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace macropage\SDKs\ebay\rest\media\Test\Api;

use \macropage\SDKs\ebay\rest\media\Configuration;
use \macropage\SDKs\ebay\rest\media\ApiException;
use \macropage\SDKs\ebay\rest\media\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * VideoApiTest Class Doc Comment
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\media
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VideoApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createVideo
     *
     * .
     *
     */
    public function testCreateVideo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getVideo
     *
     * .
     *
     */
    public function testGetVideo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadVideo
     *
     * .
     *
     */
    public function testUploadVideo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
